import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Redefinir senha",
  description: "Generated by create next app"
};

export const ResetPassLayout = ({ children }: { children: React.ReactNode }) => {
  return <AuthProvider>{children}</AuthProvider>;
};

export default ResetPassLayout;
