"use client";
import "@/styles/globals.css";
import "@/styles/typograph.css";
import "@/styles/buttons.css";
import "@/styles/inputs.css";

import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Cadastrar",
  description: "Generated by create next app"
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return <AuthProvider>{children}</AuthProvider>;
};

export default RootLayout;
