"use client";

import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Cadastrar",
  description: "Generated by create next app"
};

const RegisterLayout = ({ children }: { children: React.ReactNode }) => {
  return <AuthProvider>{children}</AuthProvider>;
};

export default RegisterLayout;
